# fly.toml app configuration file generated for ada-young on 2024-11-09T18:39:36+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'ada-young'
primary_region = 'iad'

[build]

[env]
  APP_STATIC_DOMAIN = 'ada-young.fly.dev'
  APP_BIND_ADDR = '0.0.0.0'
  APP_RECAPTCHA_KEY = '6Lfbq7kUAAAAAFd4LBuoZZV4x6lf4fwtTDGRqEnM'
  APP_CSRF_SECURE_COOKIE = true
  RUST_LOG = 'debug'

[http_service]
  internal_port = 2024
  force_https = true
  auto_stop_machines = 'suspend'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']
  [http_service.http_options.response]
    pristine = true

[[vm]]
  size = 'shared-cpu-1x'
  memory = "256mb"
  cpus = 1
  cpu_kind = "shared"
